//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESIDENTITY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDMilitants
    {
        public int idDistrict { get; set; }
        public int idRegion { get; set; }
        public int idFederation { get; set; }
        public Nullable<long> IDENTID { get; set; }
    }
}
