//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESIDENTITY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GESIDENTITYEntities : DbContext
    {
        public GESIDENTITYEntities()
            : base("name=GESIDENTITYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bases> Bases { get; set; }
        public virtual DbSet<BI> BI { get; set; }
        public virtual DbSet<Departements> Departements { get; set; }
        public virtual DbSet<Districts> Districts { get; set; }
        public virtual DbSet<Federations> Federations { get; set; }
        public virtual DbSet<FonctionParti> FonctionParti { get; set; }
        public virtual DbSet<Fonctions> Fonctions { get; set; }
        public virtual DbSet<Parametres> Parametres { get; set; }
        public virtual DbSet<Permissions> Permissions { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<Sections> Sections { get; set; }
        public virtual DbSet<Utilisateurs> Utilisateurs { get; set; }
        public virtual DbSet<NaturePiece> NaturePiece { get; set; }
        public virtual DbSet<Organes> Organes { get; set; }
        public virtual DbSet<Identifications> Identifications { get; set; }
        public virtual DbSet<IDMilitants> IDMilitants { get; set; }
    }
}
