//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESIDENTITY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametres
    {
        public int idParametre { get; set; }
        public Nullable<long> IDENTID { get; set; }
        public Nullable<long> DT { get; set; }
        public Nullable<long> RG { get; set; }
        public Nullable<long> DP { get; set; }
        public Nullable<long> FD { get; set; }
        public Nullable<long> SC { get; set; }
        public Nullable<long> BA { get; set; }
    }
}
