//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESIDENTITY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permissions()
        {
            this.Permissions1 = new HashSet<Permissions>();
            this.Utilisateurs = new HashSet<Utilisateurs>();
        }
    
        public int IdPermission { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public string Type { get; set; }
        public Nullable<int> idParent { get; set; }
        public string Path { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> EstRapport { get; set; }
        public string Etat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permissions> Permissions1 { get; set; }
        public virtual Permissions Permissions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilisateurs> Utilisateurs { get; set; }
    }
}
